### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by moose56** [developit/modify-babel-preset#11]
When running this on Windows settings do no appear to be modified.

On investigation it looks like 

``` javascript
function getModuleName(path) {
    return path.replace(/(?:..\/)*(?:(?:.+[\\/])?node_modules[\\/]|[\\/]|\.\.[\\/])((@[^\\/]+[\\/])?[^\\/]+)([\\/].*)?$/g, '$1');
}
```

does not behave as expected on Windows. An example is if passed the value 

```
..\\..\\babel-plugin-transform-es2015-modules-commonjs
```

the value 

```
..
```

is returned.

**Comment by developit** [comment]
@moose56 how come the directory name doesn't include node_modules?

**Comment by moose56** [comment]
Not sure, but running the same code on a linux machine with

```
..//..//babel-plugin-transform-es2015-modules-commonjs
```

returns 

```
babel-plugin-transform-es2015-modules-commonjs
```

which is expected.

Originally raised an [issue](https://github.com/rollup/rollup/issues/868) with Rollup as I could not get there tutorial to work on Windows. 

Finally narrowed it down to the babel-preset-es2015-rollup module not correctly changing the babel-preset-es2015 presets because modify-babel-preset cannot extract the name because of the \ in the path.

**Comment by developit** [comment]
Interesting - what are the double slashes coming from?  When I test with either of those values with single slashes it works fine, the doubles actually seem to be what's tripping it up.

**Comment by developit** [comment]
@moose56 for example, adding this `.replace()` seems to fix that case:

``` js
// strip a nested module path + filename down to just the innermost module's (file)name
function getModuleName(path) {
  return path
    .replace(/(?:(\\)\\|(\/)\/)/g, '$1$2')
    .replace(/(?:..[\\/])*(?:(?:.+[\\/])?node_modules[\\/]|[\\/]|\.\.[\\/])((@[^\\/]+[\\/])?[^\\/]+)([\\/].*)?$/g, '$1');
}
```

**Comment by moose56** [comment]
I though it might be easy to fix by swapping out the slashes although the regex is a little beyond my current abilities.

I have attached the simple example I was looking at: [rollup.zip](https://github.com/developit/modify-babel-preset/files/427632/rollup.zip)

If you run `npm install` and then `rollup -c` assuming you have rollup globally installed it works on Linux/Mac but you get an error on Windows.

The error is caused by this code

``` javascript
var modify = require('modify-babel-preset');

module.exports = modify('es2015', {
    // remove commonjs transform
    'transform-es2015-modules-commonjs': false,

    // add external helpers
    'external-helpers': true
});
```

in the babel-preset-es2015-rollup module not applying the modifications properly because it cannot match the property names.

**Comment by sorgloomer** [comment]
This was fixed in 9ae3ec, and was released as 3.0.0.

babel-plugin-es2015-rollup uses {"modify-babel-preset": "^2.1.1"} dependency.

I think it would be the simplest and best to release a 2.1.2 version with the same code as 3.0.0

**Comment by mkstix6** [comment]
Hi guys. Just looking for a little advice. I know this issue is closed but I *think* I'm coming up against this today with an older project.

I haven't seen a v2.1.2 listed. v2.1.1 looks to be the most recent v2.x.x. Please do correct me if I'm wrong.

Would v2.1.2 be on the way or would it be best to go down the path of trying to upgrade to version 3?

**Comment by moose56** [comment]
Out of interest what are you trying to transform with this plugin?

**Comment by developit** [comment]
Definitely update to version 3 - it shouldn't have been a major version, was just because it started supporting parameterized presets (since Babel itself did).
