### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by sorrycc** [developit/modify-babel-preset#5]
It don't work [pnpm](https://github.com/rstacruz/pnpm), which use link to organize node_module.

**Comment by developit** [comment]
@sorrycc Thanks for the report - I'll look into this.  I guess it's just not following symlinks?

**Comment by developit** [comment]
It seems likely that this works as of `modify-babel-preset` 3.0.  Can anyone test?

**Comment by developit** [comment]
This should be fixed by #16, much thanks to @renaesop!
