### ISSUE TITLE
Could this be used if im requiring es2015 from .babelrc?

### ISSUE THREAD

**Issue by psypersky** [developit/modify-babel-preset#7]
Hey all, i have my .babelrc file and i want to remove the transform iterators plugin, is it possible?

**Comment by developit** [comment]
Since `.babelrc` is json, you would have to create a module that does the modification and then set that as your preset instead of es2015.

**Comment by developit** [comment]
**.babelrc:**

``` js
{
  "presets": ["./my-es2015"]
}
```

**my-es2015.js:**

``` js
var modify = require('modify-babel-preset');
module.exports = modify('es2015', {
  'transform-es2015-for-of': false,
  'transform-regenerator': false
});
```

**Comment by psypersky** [comment]
Great, got it working thanks!
