### ISSUE TITLE
wrong relative path

### ISSUE THREAD

**Issue by zdying** [developit/modify-babel-preset#9]
hi, 
I have a tool(`hiipack`, path: `/Users/zdying/hiipack`) based on webpack
and a front end project : `/Users/zdying/test`

when i exec the command to build `test`(use `babel-preset-es2015-loose`), now the `process.cwd()` is `/Users/zdying/test`,  then `modify-babel-preset` find `es2015` from ‌["/Users/zdying/test/node_modules","/Users/zdying/node_modules","/Users/node_modules"].
the result is an error occurred： 

```
ERROR in ./todo/src/main.js
Module build failed: Error: Cannot find module 'es2015'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/zdying/hiipack/node_modules/modify-babel-preset/index.js:35:23)
    at Object.<anonymous> (/Users/zdying/hiipack/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /Users/zdying/hiipack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/zdying/hiipack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
```

**Because the method `getModule(dir)`'s (in `require-relative` ) param if not pass， it give the `process.cwd()` to it.**

```
var getModule = function(dir) {
  var rootPath = dir ? path.resolve(dir) : process.cwd();
  var rootName = path.join(rootPath, '@root');
  var root = modules[rootName];
  if (!root) {
    root = new Module(rootName);
    root.filename = rootName;
    root.paths = Module._nodeModulePaths(rootPath);
    modules[rootName] = root;
  }
  return root;
};
```

i think the relative path should be `/Users/zdying/hiipack`, not be `/Users/zdying/test`.
Could someone fix it?

**Comment by developit** [comment]
I don't think I'm fully understanding the situation here - it seems like you need `modify-babel-preset` to start module resolution from a directory other than the CWD, but how would it know which directory?  Perhaps something like `path.dirname(__dirname)` would work?  That would theoretically give the root directory of the module that imported `modify-babel-preset`...

**Comment by zdying** [comment]
@developit 

>  That would theoretically give the root directory of the module that imported modify-babel-preset

I think this will work. but how to give the root directory?

**Comment by developit** [comment]
@zdying might have to modify the library itself

**Comment by jimthedev** [comment]
I think this is also an issue in react-native's packager. Horizon.io's client uses es2015-loose and when you include the client in a react-native project it looks in the wrong folder.

**Comment by zdying** [comment]
@jimthedev i think it's better that `babel` provides a config field line webpack's  `resolve.fallback`.

**Comment by jimthedev** [comment]
@zdying Sorry, I am not sure I understand. Are you saying that babel should provide a field similar to webpack's resolve.fallback? It seems there is some ongoing discussion here about similar issues: https://github.com/babel/babel-loader/issues/149

**Comment by zdying** [comment]
@jimthedev 

Currently. i give the absolute path to `preset` and `plugin` to fix it. 

[https://github.com/zdying/hiipack/blob/1.0.1/tmpl/vue/config.js#L31-L36](https://github.com/zdying/hiipack/blob/1.0.1/tmpl/vue/config.js#L31-L36)

the `__hiipack__.resolve(module)` will found `module` from multiple directories
and return the absolute path of the `module`. but: 

> Are you saying that babel should provide a field similar to webpack's resolve.fallback

i think this is a better solution.

**Comment by developit** [comment]
@zdying Pre-resolving to the absolute plugin path is actually how I'm doing this as well.  I'm just using `require.resolve()` though.

**Comment by zdying** [comment]
@developit yes, `require.resolve()` should work fine. but `hiipack` can find dependencies from other dir(like `hiipack`'s node_modules or the system tmp dir) beside the current project,  so the user do not need to manually install the dependencies,  just need to config their loaders or plugins like:

```
loaders: {
    // 所有环境下（`hii pack`）都使用
    '*': [
        { test: /\.vue$/, loader: 'vue' }
    ]
},
vue: {
    loaders: {
        js: 'babel-loader?presets[]=' + __hiipack__.resolve('babel-preset-es2015-loose')
          + '&plugins[]=' + __hiipack__.resolve('babel-plugin-transform-runtime') + '&comments=false'
    }
}
```

you can fond a config example from : [https://github.com/zdying/hiipack/blob/master/tmpl/vue/config.js#L25-L36](https://github.com/zdying/hiipack/blob/master/tmpl/vue/config.js#L25-L36)

So, i have a method `__hiipack__.resolve(module_name)` and i use it. :)

**Comment by rclmenezes** [comment]
Yup, I've been bitten by this issue, too. It seems that the `require-relative` library you use expects two parameters:

`relative('./my-path', '/a/directory/here')`

And `modify-babel-preset` calls it with one param:

https://github.com/developit/modify-babel-preset/blob/master/index.js#L71

When the second parameter is not provided, the `require-relative` library falls back to process.cwd():

https://github.com/kamicane/require-relative/blob/master/index.js#L11

This means that if I'm in a different working directory than my node_modules and I call a script that uses modify-babel-preset, it will fail to import whatever preset I'm extending.

I see two options:

1) Replace `relative.resolve('babel-preset-'+presetInput)` with `relative.resolve('babel-preset-'+presetInput, __dirname)`. This works for me and I've submitted a pull request (https://github.com/developit/modify-babel-preset/pull/12)

2) Find an alternative to require-relative. I'm nervous about depending on a library that hasn't been active in three years.

Thanks!

**Comment by jimthedev** [comment]
@developit any chance the above pr could be merged and released?

**Comment by developit** [comment]
Can do tomorrow!

**Comment by developit** [comment]
Released in [3.1.0](https://github.com/developit/modify-babel-preset/releases/tag/3.1.0)!

**Comment by jimthedev** [comment]
Thanks @developit!

**Comment by zdying** [comment]
Thanks @developit!

**Comment by zdying** [comment]
Thanks @rclmenezes
